[build]
  publish = "public/"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Feature-Policy = "accelerometer 'none'; camera 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; payment 'none'; usb 'none'"
    Content-Security-Policy = "default-src 'self'; script-src www.google-analytics.com 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src data: www.google-analytics.com stats.g.doubleclick.net 'self'; frame-src: www.youtube.com 'self'; font-src 'self'; form-action 'self'"